batalla_elementos: main.o Agua.o Aire.o Fuego.o funciones.o Lista.o Nodo.o Personaje.o Tierra.o
    g++ main.o Agua.o Aire.o Fuego.o funciones.o Lista.o Nodo.o Personaje.o Tierra.o -o batalla_elementos

main.o: main.cpp
    g++ -c main.cpp

Agua.o: Agua.cpp
    g++ -c Agua.cpp

Aire.o: Aire.cpp
    g++ -c Aire.cpp

Fuego.o: Fuego.cpp
    g++ -c Fuego.cpp

funciones.o: funciones.cpp
    g++ -c funciones.cpp

Lista.o: Lista.cpp
    g++ -c Lista.cpp

Nodo.o: Nodo.cpp
    g++ -c Nodo.cpp

Personaje.o: Personaje.cpp
    g++ -c Personaje.cpp

Tierra.o: Tierra.cpp
    g++ -c Tierra.cpp